### ISSUE TITLE
Uncaught ReferenceError: define is not defined

### ISSUE THREAD

**Issue by KyleOS** [kyso-io/docker#3] opened 2018-11-09 11:25 UTC
Get this console error in every Jupyterlab environment. Doesn't seem to affect anything. 

```Uncaught ReferenceError: define is not defined
    at <anonymous>:1:21
    at NotebookPanelLayout.push.HWBy.PanelLayout.attachWidget (panellayout.js:210)
    at NotebookPanelLayout.push.HWBy.PanelLayout.insertWidget (panellayout.js:113)
    at Notebook._insertCell (widget.js:343)
    at algorithm_1.each.value (widget.js:298)
    at Object.each (iter.js:60)
    at Notebook._onCellsChanged (widget.js:297)
    at invokeSlot (index.js:475)
    at Object.emit (index.js:433)
    at Signal.push.qUp9.Signal.emit (index.js:106)
```

**Comment by eoinmurray** [comment] 2018-11-30 07:04
duplicate of https://github.com/kyso-io/ui/issues/197

**Closed as completed by eoinmurray** 2018-11-30 07:04 UTC
Labels: bug
